language: erlang
before_install:
- ssh-keyscan git.herokai.com >> ~/.ssh/known_hosts
script: "mkdir -p logs; rebar compile && ct_run -dir test/ -logdir logs -pa ebin"
otp_release:
  - R16B
  - R15B02
notifications:
  email: false
  hipchat:
    rooms:
      secure: "He7izNyjirrbpNSi3KSmItOhnqyDL58t5Ig5MbMpRxOIR7Z1mHNg5ZeOaUcCxXczHXTVOO6gg+v0DHM38f4r4PLlLrqLPx/ewRUiR0gjEjK63FVQ1FyRXrQBo/2bMU2sQpcO2uK6uDdS0UK2D9/1YZp6CZ/qR2SlHua6MLiJSTM="
    template:
    - ! '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
